version: '3'
services:
  nginx:
    depends_on:
      - restservice
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  restservice:
    build:
      dockerfile: Dockerfile
      context: ./restservice
    ports:
      - '8080:8080'